"""new looked and fame on user

Revision ID: 05d0e35fd218
Revises: 4bfdcfd524e9
Create Date: 2019-03-08 17:56:12.512101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d0e35fd218'
down_revision = '4bfdcfd524e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('looks',
    sa.Column('looks_id', sa.Integer(), nullable=True),
    sa.Column('looked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['looked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['looks_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('looks')
    # ### end Alembic commands ###
