"""likes

Revision ID: 464283d1ddb0
Revises: 11f7e15ac287
Create Date: 2019-02-26 15:59:12.547489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464283d1ddb0'
down_revision = '11f7e15ac287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('likes_id', sa.Integer(), nullable=True),
    sa.Column('liked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['likes_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
